# Задание

Есть мнение: раньше снимали настоящее кино, не то что сейчас. Ваша задача — проверить это утверждение, используя файлы с рейтингами фильмов movies_stats.csv. То есть проверить, верно ли, что с ростом года выпуска фильма средний рейтинг становится ниже.

In [1]:
import pandas as pd                   # С помощью библиотеки pandas можно прочитать
df = pd.read_csv ('movies_stats.csv') # файл к заданию, movies_stats.csv
df.head()                             # и вывести первые пять строк таблицы

,userId,movieId,rating,timestamp,title,genres
0,1,31,2.5,1260759144,Dangerous Minds (1995),Drama
1,1,1029,3.0,1260759179,Dumbo (1941),Animation|Children|Drama|Musical
2,1,1061,3.0,1260759182,Sleepers (1996),Thriller
3,1,1129,2.0,1260759185,Escape from New York (1981),Action|Adventure|Sci-Fi|Thriller
4,1,1172,4.0,1260759205,Cinema Paradiso (Nuovo cinema Paradiso) (1989),Drama

При этом мы не будем затрагивать субъективные факторы этих рейтингов, а пройдёмся по следующему алгоритму:

### 1. Переменная years
В переменную years запишите список из всех годов с 1950-го по 2010-й.

In [4]:
years = list(range(1950, 2011)) # Список годов с 1950 по 2010

### 2. Функция production_year
Напишите функцию production_year, которая каждой строке из названия фильма выставляет год выпуска (год выпуска берём из столбца title). Не все названия фильмов содержат год выпуска в одинаковом формате, поэтому используйте следующий алгоритм:

1. для каждой строки пройдите по всем годам списка years;
2. если номер года присутствует в названии фильма, то функция возвращает этот год как год выпуска;
3. если ни один из номеров года списка years не встретился в названии фильма, то возвращается 1900 год.

In [5]:
def production_year(text, years_list):   # Функция production_year
    text = str(text)                     # Превращаем в строку на случай, если в ячейке NaN или число
   
    for year in years_list:              # 1. Проходим по элементам списка years
        if  str(year) in text:           # 2. Номер года переводим в строку и ищем в названии фильма
            return year                  # 2. Если номер года есть в названии - возвращаем значение
    
    return 1900                          # 3. Если год не встретился в названии - возвращаем 1900

###   3. Столбец year
Запишите год выпуска фильма по алгоритму пункта 2 в новый столбец ‘year’

In [5]:
# Столбец  year с результатами  применения  фунции production_year к столбцу title и спискy years
df['year'] = df['title'].apply(lambda x: production_year(x, years))   
df.head()
# В первой строке год был не из списка (1941), поэтому отобразился 1900

,userId,movieId,rating,timestamp,title,genres,year
0,1,31,2.5,1260759144,Dangerous Minds (1995),Drama,1995
1,1,1029,3.0,1260759179,Dumbo (1941),Animation|Children|Drama|Musical,1900
2,1,1061,3.0,1260759182,Sleepers (1996),Thriller,1996
3,1,1129,2.0,1260759185,Escape from New York (1981),Action|Adventure|Sci-Fi|Thriller,1981
4,1,1172,4.0,1260759205,Cinema Paradiso (Nuovo cinema Paradiso) (1989),Drama,1989

### 4. Рейтинг по убыванию
Посчитайте средний рейтинг всех фильмов для каждого значения столбца ‘year’ и отсортируйте результат по убыванию рейтинга.

In [14]:
# Для подсчета среднего значения mean рейтинга необходимо применить группировку groupby по годам, 
# для сортировки - reset_index (при группировке год стал индексом) и sort_values, ascending=False т.к. по убыванию
df.groupby('year').rating.mean().reset_index().sort_values('rating', ascending=False)

    year    rating
8   1957  4.014241
23  1972  4.011136
3   1952  4.000000
5   1954  3.994220
2   1951  3.983539
..   ...       ...
56  2005  3.448434
54  2003  3.444777
47  1996  3.426600
48  1997  3.415764
51  2000  3.356104

[62 rows x 2 columns]